/*
Copyright (c) 2023 SAP SE

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/sap/clustersecret-operator/pkg/apis/core.cs.sap.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterSecretLister helps list ClusterSecrets.
// All objects returned here must be treated as read-only.
type ClusterSecretLister interface {
	// List lists all ClusterSecrets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterSecret, err error)
	// Get retrieves the ClusterSecret from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterSecret, error)
	ClusterSecretListerExpansion
}

// clusterSecretLister implements the ClusterSecretLister interface.
type clusterSecretLister struct {
	indexer cache.Indexer
}

// NewClusterSecretLister returns a new ClusterSecretLister.
func NewClusterSecretLister(indexer cache.Indexer) ClusterSecretLister {
	return &clusterSecretLister{indexer: indexer}
}

// List lists all ClusterSecrets in the indexer.
func (s *clusterSecretLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterSecret, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterSecret))
	})
	return ret, err
}

// Get retrieves the ClusterSecret from the index for a given name.
func (s *clusterSecretLister) Get(name string) (*v1alpha1.ClusterSecret, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clustersecret"), name)
	}
	return obj.(*v1alpha1.ClusterSecret), nil
}
