/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and clustersecret-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterSecretListerExpansion allows custom methods to be added to
// ClusterSecretLister.
type ClusterSecretListerExpansion interface{}
