/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and clustersecret-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/clustersecret-operator/pkg/apis/core.cs.sap.com/v1alpha1"
	corecssapcomv1alpha1 "github.com/sap/clustersecret-operator/pkg/client/applyconfiguration/core.cs.sap.com/v1alpha1"
	typedcorecssapcomv1alpha1 "github.com/sap/clustersecret-operator/pkg/client/clientset/versioned/typed/core.cs.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterSecrets implements ClusterSecretInterface
type fakeClusterSecrets struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterSecret, *v1alpha1.ClusterSecretList, *corecssapcomv1alpha1.ClusterSecretApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeClusterSecrets(fake *FakeCoreV1alpha1) typedcorecssapcomv1alpha1.ClusterSecretInterface {
	return &fakeClusterSecrets{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterSecret, *v1alpha1.ClusterSecretList, *corecssapcomv1alpha1.ClusterSecretApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clustersecrets"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterSecret"),
			func() *v1alpha1.ClusterSecret { return &v1alpha1.ClusterSecret{} },
			func() *v1alpha1.ClusterSecretList { return &v1alpha1.ClusterSecretList{} },
			func(dst, src *v1alpha1.ClusterSecretList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterSecretList) []*v1alpha1.ClusterSecret {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterSecretList, items []*v1alpha1.ClusterSecret) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
