/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and clustersecret-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corecssapcomv1alpha1 "github.com/sap/clustersecret-operator/pkg/apis/core.cs.sap.com/v1alpha1"
	applyconfigurationcorecssapcomv1alpha1 "github.com/sap/clustersecret-operator/pkg/client/applyconfiguration/core.cs.sap.com/v1alpha1"
	scheme "github.com/sap/clustersecret-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterSecretsGetter has a method to return a ClusterSecretInterface.
// A group's client should implement this interface.
type ClusterSecretsGetter interface {
	ClusterSecrets() ClusterSecretInterface
}

// ClusterSecretInterface has methods to work with ClusterSecret resources.
type ClusterSecretInterface interface {
	Create(ctx context.Context, clusterSecret *corecssapcomv1alpha1.ClusterSecret, opts v1.CreateOptions) (*corecssapcomv1alpha1.ClusterSecret, error)
	Update(ctx context.Context, clusterSecret *corecssapcomv1alpha1.ClusterSecret, opts v1.UpdateOptions) (*corecssapcomv1alpha1.ClusterSecret, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterSecret *corecssapcomv1alpha1.ClusterSecret, opts v1.UpdateOptions) (*corecssapcomv1alpha1.ClusterSecret, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corecssapcomv1alpha1.ClusterSecret, error)
	List(ctx context.Context, opts v1.ListOptions) (*corecssapcomv1alpha1.ClusterSecretList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corecssapcomv1alpha1.ClusterSecret, err error)
	Apply(ctx context.Context, clusterSecret *applyconfigurationcorecssapcomv1alpha1.ClusterSecretApplyConfiguration, opts v1.ApplyOptions) (result *corecssapcomv1alpha1.ClusterSecret, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterSecret *applyconfigurationcorecssapcomv1alpha1.ClusterSecretApplyConfiguration, opts v1.ApplyOptions) (result *corecssapcomv1alpha1.ClusterSecret, err error)
	ClusterSecretExpansion
}

// clusterSecrets implements ClusterSecretInterface
type clusterSecrets struct {
	*gentype.ClientWithListAndApply[*corecssapcomv1alpha1.ClusterSecret, *corecssapcomv1alpha1.ClusterSecretList, *applyconfigurationcorecssapcomv1alpha1.ClusterSecretApplyConfiguration]
}

// newClusterSecrets returns a ClusterSecrets
func newClusterSecrets(c *CoreV1alpha1Client) *clusterSecrets {
	return &clusterSecrets{
		gentype.NewClientWithListAndApply[*corecssapcomv1alpha1.ClusterSecret, *corecssapcomv1alpha1.ClusterSecretList, *applyconfigurationcorecssapcomv1alpha1.ClusterSecretApplyConfiguration](
			"clustersecrets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corecssapcomv1alpha1.ClusterSecret { return &corecssapcomv1alpha1.ClusterSecret{} },
			func() *corecssapcomv1alpha1.ClusterSecretList { return &corecssapcomv1alpha1.ClusterSecretList{} },
		),
	}
}
