name: Check Go license boilerplate
description: Check license boilerplate used in Go files
inputs:
  boilerplate-path:
    description: License boilerplate file path
    required: true
  boilerplate-content:
    description: License boilerplate content
    default: |-
      /*
      SPDX-FileCopyrightText: ${YEAR} SAP SE or an SAP affiliate company and ${REPOSITORY} contributors
      SPDX-License-Identifier: Apache-2.0
      */
runs:
  using: composite
  steps:
  - name: Check boilerplate file
    shell: bash
    env:
      INPUT_BOILERPLATE_PATH: ${{ inputs.boilerplate-path }}
      INPUT_BOILERPLATE_CONTENT: ${{ inputs.boilerplate-content }}
    run: |
      this_year=$(date +%Y)
      last_year=$((this_year-1))
      repository=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)

      tempdir=$(mktemp -d)
      trap 'rm -rf $tempdir' EXIT

      printenv INPUT_BOILERPLATE_CONTENT | YEAR=$this_year REPOSITORY=$repository envsubst > $tempdir/boilerplate-this-year
      printenv INPUT_BOILERPLATE_CONTENT | YEAR=$last_year REPOSITORY=$repository envsubst > $tempdir/boilerplate-last-year

      if diff -q $INPUT_BOILERPLATE_PATH $tempdir/boilerplate-this-year >/dev/null; then
        exit 0
      fi
      if diff -q $INPUT_BOILERPLATE_PATH $tempdir/boilerplate-last-year >/dev/null; then
        >&1 echo "Warning: license boilerplate outdated ($last_year); next year, this will result in an error."
        exit 0
      fi

      >&1 echo "Error: incorrect license boilerplate."
      exit 1
