name: Setup semver
description: Setup semver
inputs:
  version: 
    description: Version
    default: latest
  install-directory:
    description: Target installation directory
    default: '$HOME/.semver/bin'
outputs:
  path:
    description: Path to the installed semver executable
    value: ${{ steps.install.outputs.path }}
runs:
  using: composite
  steps:
  - name: Install semver
    id: install
    shell: bash
    run: |
      version=${{ inputs.version}}
      install_directory=${{ inputs.install-directory }}
      if [ "$version" == latest ]; then
        version=master
      fi
      mkdir -p "$install_directory"
      curl -sSf -L -o "$install_directory/semver" https://raw.githubusercontent.com/fsaintjacques/semver-tool/$version/src/semver
      chmod a+x "$install_directory/semver"
      echo "$install_directory" >> $GITHUB_PATH
      echo "path=$install_directory/semver" >> $GITHUB_OUTPUT