/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and clustersecret-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscorecssapcomv1alpha1 "github.com/sap/clustersecret-operator/pkg/apis/core.cs.sap.com/v1alpha1"
	versioned "github.com/sap/clustersecret-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sap/clustersecret-operator/pkg/client/informers/externalversions/internalinterfaces"
	corecssapcomv1alpha1 "github.com/sap/clustersecret-operator/pkg/client/listers/core.cs.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterSecretInformer provides access to a shared informer and lister for
// ClusterSecrets. Prefer using the type-safe variant (see [TypedClusterSecretInformer]).
type ClusterSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corecssapcomv1alpha1.ClusterSecretLister
}

// TypedClusterSecretInformer provides access to a shared informer and lister for
// ClusterSecrets, including the type-safe TypedInformer variant.
// It is a superset of ClusterSecretInformer.
type TypedClusterSecretInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ClusterSecretIndexInformer
	Lister() corecssapcomv1alpha1.ClusterSecretLister
}

// ClusterSecretIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ClusterSecretIndexInformer cache.TypedSharedIndexInformer[*apiscorecssapcomv1alpha1.ClusterSecret]

// ClusterSecretHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for ClusterSecret.
type ClusterSecretHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiscorecssapcomv1alpha1.ClusterSecret]

// ClusterSecretDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for ClusterSecret.
type ClusterSecretDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiscorecssapcomv1alpha1.ClusterSecret]

// ClusterSecretFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for ClusterSecret.
type ClusterSecretFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiscorecssapcomv1alpha1.ClusterSecret]

// ClusterSecretIndexers is a specialization of [cache.TypedIndexers] for ClusterSecret.
type ClusterSecretIndexers = cache.TypedIndexers[*apiscorecssapcomv1alpha1.ClusterSecret]

// DeletedClusterSecret is a specialization of [cache.DeletedObject] for ClusterSecret.
type DeletedClusterSecret = cache.DeletedObject[*apiscorecssapcomv1alpha1.ClusterSecret]

type clusterSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterSecretInformer constructs a new informer for ClusterSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterSecretInformer]).
func NewClusterSecretInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewClusterSecretInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedClusterSecretInformer constructs a new informer for ClusterSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterSecretInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterSecretIndexers) ClusterSecretIndexInformer {
	return NewTypedClusterSecretInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredClusterSecretInformer constructs a new informer for ClusterSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredClusterSecretInformer]).
func NewFilteredClusterSecretInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedClusterSecretInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredClusterSecretInformer constructs a new informer for ClusterSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredClusterSecretInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterSecretIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterSecretIndexInformer {
	return NewTypedClusterSecretInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewClusterSecretInformerWithOptions constructs a new informer for ClusterSecret type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterSecretInformerWithOptions]).
func NewClusterSecretInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedClusterSecretInformerWithOptions(client, options)
}

// NewTypedClusterSecretInformerWithOptions constructs a new informer for ClusterSecret type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterSecretInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) ClusterSecretIndexInformer {
	gvr := schema.GroupVersionResource{Group: "core.cs.sap.com", Version: "v1alpha1", Resource: "clustersecrets"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiscorecssapcomv1alpha1.ClusterSecret](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().ClusterSecrets().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().ClusterSecrets().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().ClusterSecrets().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().ClusterSecrets().Watch(ctx, opts)
			},
		}, client),
		&apiscorecssapcomv1alpha1.ClusterSecret{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *clusterSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedClusterSecretInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *clusterSecretInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *clusterSecretInformer) TypedInformer() ClusterSecretIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscorecssapcomv1alpha1.ClusterSecret](f.factory.InformerFor(&apiscorecssapcomv1alpha1.ClusterSecret{}, f.defaultInformer))
}

func (f *clusterSecretInformer) Lister() corecssapcomv1alpha1.ClusterSecretLister {
	return corecssapcomv1alpha1.NewClusterSecretLister(f.Informer().GetIndexer())
}

// ToTypedClusterSecretInformer converts an untyped informer into a TypedClusterSecretInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterSecret. If that is not the case, calling type-safe methods of the returned
// TypedClusterSecretInformer leads to runtime panics. A safer alternative is to pass
// around a TypedClusterSecretInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedClusterSecretInformer(informer ClusterSecretInformer) TypedClusterSecretInformer {
	if informer, ok := informer.(TypedClusterSecretInformer); ok {
		return informer
	}
	return &clusterSecretTypedInformerAdapter{informer}
}

type clusterSecretTypedInformerAdapter struct {
	ClusterSecretInformer
}

func (a *clusterSecretTypedInformerAdapter) TypedInformer() ClusterSecretIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscorecssapcomv1alpha1.ClusterSecret](a.Informer())
}

// ToClusterSecretIndexInformer converts an untyped informer into a ClusterSecretIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterSecret. If that is not the case, calling type-safe methods of the returned
// ClusterSecretIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ClusterSecretIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToClusterSecretIndexInformer(informer cache.SharedIndexInformer) ClusterSecretIndexInformer {
	if informer, ok := informer.(ClusterSecretIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiscorecssapcomv1alpha1.ClusterSecret](informer)
}
