/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and clustersecret-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	corecssapcomv1alpha1 "github.com/sap/clustersecret-operator/pkg/apis/core.cs.sap.com/v1alpha1"
	versioned "github.com/sap/clustersecret-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sap/clustersecret-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/sap/clustersecret-operator/pkg/client/listers/core.cs.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterSecretInformer provides access to a shared informer and lister for
// ClusterSecrets.
type ClusterSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterSecretLister
}

type clusterSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterSecretInformer constructs a new informer for ClusterSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterSecretInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterSecretInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterSecretInformer constructs a new informer for ClusterSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterSecretInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().ClusterSecrets().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().ClusterSecrets().Watch(context.TODO(), options)
			},
		},
		&corecssapcomv1alpha1.ClusterSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterSecretInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corecssapcomv1alpha1.ClusterSecret{}, f.defaultInformer)
}

func (f *clusterSecretInformer) Lister() v1alpha1.ClusterSecretLister {
	return v1alpha1.NewClusterSecretLister(f.Informer().GetIndexer())
}
