---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: clustersecret-operator
webhooks:
- name: clustersecret-operator.cs.sap.com
  admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ${CACERT}
    url: https://${HOST}:2443/validation
  rules:
  - apiGroups:
    - core.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clustersecrets
    scope: Cluster
  matchPolicy: Exact
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: clustersecret-operator
webhooks:
- name: clustersecret-operator.cs.sap.com
  admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ${CACERT}
    url: https://${HOST}:2443/mutation
  rules:
  - apiGroups:
    - core.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clustersecrets
    scope: Cluster
  matchPolicy: Exact
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail
