---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: clustersecret-operator
webhooks:
- name: validate.clustersecrets.core.cs.sap.com
  admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ${WEBHOOK_CA_CERT}
    url: https://${WEBHOOK_HOSTNAME}:2443/validation
  rules:
  - apiGroups:
    - core.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clustersecrets
    scope: Cluster
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail