name: Publish Custom Resource Definitions

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Setup regctl
      run: |
        curl -sSf -L -o $RUNNER_TEMP/regctl https://github.com/regclient/regclient/releases/download/v0.4.8/regctl-linux-amd64
        chmod a+x $RUNNER_TEMP/regctl

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the registry
      run: |
        $RUNNER_TEMP/regctl registry login $REGISTRY --user ${{ github.actor }} --pass-stdin <<< ${{ secrets.GITHUB_TOKEN }}

    - name: Build artifact
      run: |
        cd crds
        repository=${{ github.repository }}/crds
        tar cvz * | $RUNNER_TEMP/regctl artifact put -m application/gzip $REGISTRY/${repository,,}:${{ github.event.release.tag_name }}