name: Trigger release

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Whether to bump major, minor or patch version'
        required: false
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch
      desired-version:
        description: 'Version to be released; if specified, version-bump will be ignored'
        required: false
        default: ''

  schedule:
    - cron: '10 7 * * 1'
    - cron: '10 8 * * 1'

concurrency: trigger-release

env:
  TAG_PREFIX: v
  INITIAL_TAG: v0.1.0
  SEMVER_VERSION: 3.4.0

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Trigger release
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Validate ref
      run: |
        if [ "${{ github.ref }}" != refs/heads/main ]; then
          >&2 echo "Invalid ref: ${{ github.ref }} (expected: refs/heads/main)"
          exit 1
        fi

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_USER_GH_TOKEN }}

    - name: Setup semver
      uses: ./.github/actions/setup-semver
      with:
        version: ${{ env.SEMVER_VERSION }}
        install-directory: ${{ runner.temp }}/bin

    - name: Determine current release
      id: get_current_release
      uses: ./.github/actions/get-highest-tag
      with:
        prefix: ${{ env.TAG_PREFIX }}

    - name: Get number of commits since current release
      id: commits
      if: github.event_name == 'schedule'
      run: |
        git fetch --tags
        echo "count=$(git rev-list --count --no-merges ${{ steps.get_current_release.outputs.tag }}..HEAD --before=1.hour)" >> $GITHUB_OUTPUT

    - name: Determine target release
      id: get_target_release
      run: |
        create_release=true
        desired_version=${{ inputs.desired-version }}
        current_version=${{ steps.get_current_release.outputs.version }}

        if "${{ github.event_name == 'schedule' }}"; then
          version_bump=patch
          commits_count=${{ steps.commits.outputs.count }}

          if [[ $commits_count -eq 0 ]]; then
            create_release=false
            >&2 echo "There are no commits since latest release found, nothing to do."
          fi
        else
          version_bump=${{ inputs.version-bump }}
        fi

        if [ -z "$desired_version" ]; then
          case $version_bump in
            major|minor|patch)
              # ok
              ;;
            *)
              >&2 echo "Invalid input: version-bump ($version_bump)."
              exit 1
          esac
          if [ -z "$current_version" ]; then
            version=${INITIAL_TAG/#$TAG_PREFIX/}
            tag=$INITIAL_TAG
          else
            version=$(semver bump $version_bump $current_version)
            tag=$TAG_PREFIX$version
          fi
        else
          if [[ $desired_version =~ ^$TAG_PREFIX([0-9].*)$ ]]; then
            version=${BASH_REMATCH[1]}
            tag=$desired_version
          else
            >&2 echo "Invalid input: desired-version ($desired_version) should start with $TAG_PREFIX."
            exit 1
          fi
          if [ "$(semver validate $version)" != valid ]; then
            >&2 echo "Invalid input: desired-version ($version) is not a valid semantic version."
            exit 1
          fi
          if [ "$(semver compare $version $current_version)" -le 0 ]; then
            >&2 echo "Invalid input: desired-version ($version) should be higher than current version ($current_version)."
            exit 1
          fi
        fi

        echo "Target version: $version"
        echo "Target tag: $tag"
        echo "Create release: $create_release"
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "create_release=$create_release" >> $GITHUB_OUTPUT

    - name: Determine target commit
      if: steps.get_target_release.outputs.create_release == 'true'
      id: get_target_commit
      run: |
        sha=$(git rev-parse HEAD)
        echo "Target commit: $sha"
        echo "sha=$sha" >> $GITHUB_OUTPUT

    - name: Wait for check suites to complete
      if: steps.get_target_release.outputs.create_release == 'true'
      uses: sap-contributions/await-check-suites@master
      with:
        ref: ${{ steps.get_target_commit.outputs.sha }}
        intervalSeconds: 10
        timeoutSeconds: 1800
        failStepIfUnsuccessful: true
        appSlugFilter: github-actions

    - name: Create Release
      if: steps.get_target_release.outputs.create_release == 'true'
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_USER_GH_TOKEN }}
      run: |
        gh release create ${{ steps.get_target_release.outputs.tag }} \
          --target "${{ steps.get_target_commit.outputs.sha }}"
